set -ga terminal-overrides ',xterm-kitty:RGB' 
set -g default-terminal "xterm-kitty"
set-option -sa terminal-overrides ",xterm*:Tc"

set -g prefix C-a
unbind C-b
bind-key C-a send-prefix


unbind %
bind | split-window -h

unbind '"'
bind - split-window -v

unbind r
bind r source-file $XDG_CONFIG_HOME/tmux/tmux.conf
bind r run "echo 'Tmux config reloaded'"

bind -r C-j resize-pane -D 5
bind -r C-k resize-pane -U 5
bind -r C-l resize-pane -R 5
bind -r C-h resize-pane -L 5

unbind f
bind -r f resize-pane -Z

unbind x
bind -r x kill-pane

unbind X
bind -r X kill-window

bind b previous-window

# Shift Alt vim keys to switch windows
bind -n M-H previous-window
bind -n M-L next-window

bind-key -T copy-mode-vi 'v' send -X begin-selection # start selecting text with "v"
bind-key -T copy-mode-vi 'y' send -X copy-selection # copy text with "y"

unbind -T copy-mode-vi MouseDragEnd1Pane # don't exit copy mode after dragging with mouse

# Open nvim in a new vertical pane above current pane with the same directory and with 85% height
bind o run "tmux split-window -v -c '#{pane_current_path}' -b -p 85 'nvim .' && tmux resize-pane -Z"

# Run lazygit in a new floating pane
bind g display-popup \
  -d '#{pane_current_path}' \
  -w 80% \
  -h 80% \
  -E "lazygit"

bind c display-popup -E 'bash -i -c "read -p \"Window name: \" name; tmux new-window -n \$name"'
bind s display-popup -E 'bash -i -c "read -p \"Session name: \" name; tmux new-session -d -s \$name && tmux switch-client -t \$name"'
bind l display-popup -E "tmux list-sessions | sed -E 's/:.*$//' | grep -v \"^$(tmux display-message -p '#S')\$\" | fzf --reverse | xargs tmux switch-client -t"
bind t display-popup \
  -d '#{pane_current_path}' \
  -E 'tmux'

# Rename session
bind M-s display-popup -E 'bash -i -c "read -p \"Session name: \" name; tmux rename-session \$name"'

# Rename window
bind M-w display-popup -E 'bash -i -c "read -p \"Window name: \" name; tmux rename-window \$name"'

# Kill server
bind M-q display-popup -E 'bash -i -c "read -p \"Kill server? \" -n 1 -r; echo; if [[ \$REPLY =~ ^[Yy]$ ]]; then tmux kill-server; fi"'

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g mouse on
set-window-option -g mode-keys vi

# Plugin manager
set -g @plugin 'tmux-plugins/tpm'

# List of plugins
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'niksingh710/minimal-tmux-status'

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-capture-pane-contents 'on'

# Status bar options
set -g @minimal-tmux-status "top"
set -g @minimal-tmux-right false
set -g @minimal-tmux-left false
set -g @minimal-tmux-use-arrow true
set -g @minimal-tmux-right-arrow ""
set -g @minimal-tmux-left-arrow ""
set -g status-right-length 20
set -g status-left-length 20

set -g 'status-format[1]' ''
set -g status 2

run "~/.tmux/plugins/tpm/tpm"
